### PR TITLE
Declare F as a list, not a set.  Fixes #48.

### LINKED ISSUE #48: the definition of F as a set of sets sounds incorrect
In the [formal semantics](http://adl.github.io/hoaf/#formal-semantics-of-omega-automata) we have something like this

> $F=\{S_0,S_1,…,S_{m−1}\}$ is a finite set of acceptance sets. 

where each S_i is a subset of transitions.

I think declaring F as a set is a mistake, because it implicitly implies that all S_i will be different, which is not the case in the format.

I suggest to rewrite this as

> $F=(S_0,S_1,…,S_{m−1})$ is a tuple of $m$ acceptance sets. 

Do you agree?

### PR DESCRIPTION
**Pull request by adl**
Here is a proposal for #48.  The list idea is from Joachim.

The inversion of F and R in the description is because m, used in R, comes from the size of F.

### CODE REVIEW

**Comment by strejcek** [comment]
The suggested order of F and R is not lucky: R precedes F in the automaton tuple and definition of F also heavily uses R, so R should be defined first.

However, the question is whether we really want/need to define F: it seems that in the current setting it just duplicates the information already described by R. Wouldn't it be cleaner to define S_i sets just before the definition of an accepting run?

**Comment by adl** [comment]
On Wed, Jun 3, 2015 at 2:13 PM, Jan Strejček <notifications@github.com> wrote:
> However, the question is whether we really want/need to define F: it seems that in the current setting it just duplicates the information already described by R. Wouldn't it be cleaner to define S_i sets just before the definition of an accepting run?

The reason we define the S_i set as part of the automaton is to make
the parallel with state-based acceptance very clear.  If you remove
the F from the transition-based definition, you need a diferent
definition for automata with state-based acceptance.  (I'm not against
it, I'm just explaining why things look the way they look.)



-- 
Alexandre Duret-Lutz

**Comment by strejcek** [comment]
Ah, I see. I'm not sure whether the benefits for state-based acceptance pays the unsightliness of the basic definition. Others?

**Comment by kleinj** [comment]
I agree that the S_i sets in the tuple for the transition-based automaton are redundant and would propose something in the spirit of the following:
* remove $F$ from the tuple for the transition-based automaton, replace by $m$ (```$m$ is the number of acceptance sets used by the automaton```), with the explanation for $R$ coming after $m$
* Afterwards, have ```The indizes of the acceptance sets appearing in the transitions induce a list of acceptance sets $F=(S_0, ..., S_{m-1})$ with $S_i \subseteq R$ containing those transitions with $i \in M$, i.e., ... [as currently]```
* For state-based acceptance, use $F$ in the tuple and in the explanation for F have a note such as ```In contrast to the automaton with transition-based acceptance, the acceptance sets $S_0, ..., S_{m-1}$ are directly defined, with each S_i being a subset of states.```

I think that this would actually improve the clarity in the transition-based case, and would not complicate the state-based definition.

**Comment by adl** [comment]
Superseded by #50.

**Pull request closed without merging**
